### PR TITLE
Python 3 changes

### PR DESCRIPTION
**Pull request by kkaiser**
Since there are no automated tests I cannot verify all the examples but the problem about inline maps not displaying should be fixed. It seems like tiles first appear black though, a reload usually helps to show the map tiles. Python version is 3.7.0

### CODE REVIEW

**Comment by timgrossmann** [comment]
@andrea-cuttone Any chance we can get this merged?

**Comment by andrea-cuttone** [comment]
sure

**Comment by timgrossmann** [comment]
@andrea-cuttone Awesome!
Do you have a pipeline setup which publishes it to PyPi to get the newest release available through pip?

**Comment by andrea-cuttone** [comment]
no, I do not. You should be able to install from source no?

**Comment by timgrossmann** [comment]
@andrea-cuttone Yes, sure!
I'd love to use your library in a lesson in a course and having a pip install would be perfect.

**Pull request merged**
